CREATE TABLESPACE kow_tbs DATAFILE 'kow_tbs.dat' SIZE 20M AUTOEXTEND ON;
CREATE UNDO TABLESPACE kow_undo_tbs DATAFILE 'kow_undo_tbs.f' SIZE 10M AUTOEXTEND ON RETENTION GUARANTEE;
CREATE TEMPORARY TABLESPACE kow_tmp_tbs TEMPFILE 'kow_tmp_tbs.dbf' SIZE 5M AUTOEXTEND ON;

CREATE USER kow IDENTIFIED BY init
    DEFAULT TABLESPACE kow_tbs QUOTA 10M ON kow_tbs;

GRANT all PRIVILEGES TO kow;